In [1]:
import pandas as pd

In [6]:
emp = pd.DataFrame({'Name':['Akshay', 'Rohit', 'Virat', 'John', 'Michael'],
                   'Age':[32, 45, 28, 32, 27],
                   'Salary':[45000, 38000, 29000, 50000, 41000]
                   })
emp

      Name  Age  Salary
0   Akshay   32   45000
1    Rohit   45   38000
2    Virat   28   29000
3     John   32   50000
4  Michael   27   41000

In [7]:
emp['Salary'].mean()

40600.0

In [8]:
emp['Salary'].median()

41000.0

In [9]:
emp['Salary'].mode()

0    29000
1    38000
2    41000
3    45000
4    50000
Name: Salary, dtype: int64

In [10]:
emp['Age'].mode()

0    32
Name: Age, dtype: int64

In [11]:
emp['Age'].unique()

array([32, 45, 28, 27], dtype=int64)

In [ ]:
emp['Age'].value_counts()               #count of unique values

Age
32    2
45    1
28    1
27    1
Name: count, dtype: int64

In [ ]:
emp['DID'] = [1, 2, 2, 3, 4]            #add new column (but it add in the last)
emp

      Name  Age  Salary  DID  dud
0   Akshay   32   45000    1    1
1    Rohit   45   38000    2    2
2    Virat   28   29000    2    3
3     John   32   50000    3    1
4  Michael   27   41000    4    4

In [26]:
emp

      Name  Age  Salary  DID
0   Akshay   32   45000    1
1    Rohit   45   38000    2
2    Virat   28   29000    2
3     John   32   50000    3
4  Michael   27   41000    4

In [28]:
emp.insert(2, value = ['Pune','Mumbai','CSN', 'Nashik', 'Akola'], column='Address')

In [29]:
emp

      Name  Age Address  Salary  DID
0   Akshay   32    Pune   45000    1
1    Rohit   45  Mumbai   38000    2
2    Virat   28     CSN   29000    2
3     John   32  Nashik   50000    3
4  Michael   27   Akola   41000    4

here if we do without loc() then it will add as a column
but now we used loc() then it will add as a row

In [ ]:
emp.loc[len(emp)] = ['Roshan', 67, 'Pune', 100000, 1]

In [32]:
emp

       Name  Age Address  Salary  DID
0    Akshay   32    Pune   45000    1
1     Rohit   45  Mumbai   38000    2
2     Virat   28     CSN   29000    2
3      John   32  Nashik   50000    3
4   Michael   27   Akola   41000    4
5    Roshan   67    Pune  100000    1
10   Roshan   67    Pune  100000    1

In [33]:
len(emp)

6

In [ ]:
#emp = emp.drop(10)
emp.drop(10, inplace=True)          #inplace means change directly into original

specific value change

In [40]:
emp.loc[emp['Name'] == 'Rohit', 'Salary'] = 80000            #(location, what to change) = updated value

In [41]:
emp

      Name  Age Address  Salary  DID
0   Akshay   32    Pune   45000    1
1    Rohit   45  Mumbai   80000    2
2    Virat   28     CSN   29000    2
3     John   32  Nashik   50000    3
4  Michael   27   Akola   41000    4
5   Roshan   67    Pune  100000    1

In [43]:
emp.loc[emp['Name'] == 'John']

   Name  Age Address  Salary  DID
3  John   32  Nashik   50000    3